# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mappaddingexample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mappaddingexample

  pod 'GoogleMaps'

  target 'mappaddingexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mappaddingexample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mappaddingexample-tvOS

  target 'mappaddingexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
